let CFG={url:'',key:''}, session=JSON.parse(localStorage.getItem('yg_session')||'null'), cart=JSON.parse(localStorage.getItem('yg_cart')||'[]'), products=[], categories=[];
const $=id=>document.getElementById(id), money=n=>Number(n||0).toLocaleString('tr-TR',{style:'currency',currency:'TRY'}), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveCart(){localStorage.setItem('yg_cart',JSON.stringify(cart));$('count').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function headers(auth=true){let h={'apikey':CFG.key,'Content-Type':'application/json'};if(auth&&session?.access_token)h.Authorization='Bearer '+session.access_token;return h}
async function rest(path,opt={}){let r=await fetch(`${CFG.url}/rest/v1/${path}`,{...opt,headers:{...headers(opt.auth!==false),...(opt.headers||{})}});if(!r.ok)throw new Error(await r.text());let t=await r.text();return t?JSON.parse(t):null}
async function auth(path,body){let r=await fetch(`${CFG.url}/auth/v1/${path}`,{method:'POST',headers:headers(false),body:JSON.stringify(body)});let j=await r.json();if(!r.ok)throw new Error(j.msg||j.error_description||j.message||'İşlem başarısız');return j}
function show(html){$('sheet').innerHTML=`<button class="x" onclick="closeModal()">×</button>${html}`;$('modal').style.display='flex'} function closeModal(){$('modal').style.display='none'}
async function boot(){try{CFG=await (await fetch('/api/config')).json();if(!CFG.url||!CFG.key)throw Error('Vercel Supabase ayarları eksik.');await loadData();}catch(e){$('products').innerHTML=`<div class='notice'>Bağlantı kurulamadı: ${esc(e.message)}</div>`}saveCart();}
async function loadData(){categories=await rest('categories?select=*&active=eq.true&order=sort_order',{auth:false})||[];products=await rest('products?select=*&active=eq.true&order=featured.desc,created_at.desc',{auth:false})||[];renderCats();renderProducts(products)}
function renderCats(){$('cats').innerHTML=categories.map(c=>`<button class='cat' onclick='filterCat(${c.id})'>${esc(c.emoji||'🛒')}<br>${esc(c.name)}</button>`).join('')}
function renderProducts(list){$('products').innerHTML=list.length?list.map(p=>`<div class='card'><div class='pic'>${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:esc(p.emoji||'🛒')}</div><b>${esc(p.name)}</b>${p.old_price?`<div class='old'>${money(p.old_price)}</div>`:''}<div class='price'>${money(p.price)}</div><small>${p.stock>0?`Stok: ${p.stock}`:'Stokta yok'}</small><button class='btn' ${p.stock<=0?'disabled':''} onclick='add(${p.id})'>Sepete +</button></div>`).join(''):`<div class='notice'>Bu bölümde ürün yok.</div>`}
function filterCat(id){renderProducts(products.filter(p=>p.category_id===id))} function searchProducts(v){v=v.toLocaleLowerCase('tr-TR');renderProducts(products.filter(p=>p.name.toLocaleLowerCase('tr-TR').includes(v)))}
function add(id){let p=products.find(x=>x.id===id);if(!p)return;let x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:p.id,name:p.name,price:Number(p.price),qty:1});saveCart();}
function openCart(){if(!cart.length)return show('<h2>Sepetim</h2><p>Sepetiniz boş.</p>');let total=cart.reduce((s,x)=>s+x.price*x.qty,0);show(`<h2>Sepetim</h2>${cart.map((x,i)=>`<div class='cartline'><span>${esc(x.name)} × ${x.qty}</span><span>${money(x.price*x.qty)} <button onclick='removeItem(${i})'>×</button></span></div>`).join('')}<h3>Toplam: ${money(total)}</h3><button class='btn' onclick='checkout()'>Siparişi Tamamla</button>`)}
function removeItem(i){cart.splice(i,1);saveCart();openCart()}
function authScreen(next=''){show(`<h2>Üye Girişi</h2><p>Adresinizi bir kez kaydedin, sonraki siparişlerde tekrar yazmayın.</p><input id='email' class='input' type='email' placeholder='E-posta'><input id='pass' class='input' type='password' placeholder='Şifre'><button class='btn' onclick="login('${next}')">Giriş Yap</button><button class='btn secondary' onclick="registerScreen('${next}')">Yeni Üyelik Oluştur</button>`)}
function registerScreen(next=''){show(`<h2>Yeni Üyelik</h2><input id='rname' class='input' placeholder='Ad Soyad'><input id='rphone' class='input' placeholder='Cep telefonu'><input id='remail' class='input' type='email' placeholder='E-posta'><input id='rpass' class='input' type='password' placeholder='Şifre (en az 6 karakter)'><textarea id='raddr' class='input' rows='3' placeholder='Teslimat adresi'></textarea><button class='btn' onclick="register('${next}')">Kayıt Ol</button>`)}
async function login(next){try{let j=await auth('token?grant_type=password',{email:$('email').value.trim(),password:$('pass').value});session=j;localStorage.setItem('yg_session',JSON.stringify(j));closeModal();if(next==='checkout')checkout();else openProfile()}catch(e){alert(e.message)}}
async function register(next){let full_name=$('rname').value.trim(),phone=$('rphone').value.trim(),email=$('remail').value.trim(),password=$('rpass').value,address=$('raddr').value.trim();if(!full_name||!phone||!email||password.length<6||!address)return alert('Tüm alanları doldurun.');try{let j=await auth('signup',{email,password});if(!j.access_token)return alert('Kayıt oluşturuldu. E-posta doğrulaması açıksa e-postanızı doğrulayıp giriş yapın.');session=j;localStorage.setItem('yg_session',JSON.stringify(j));await rest('profiles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:j.user.id,full_name,phone})});await rest('addresses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:j.user.id,title:'Ev',address,is_default:true})});closeModal();if(next==='checkout')checkout();else openProfile()}catch(e){alert(e.message)}}
async function profile(){if(!session)return null;let p=(await rest(`profiles?select=*&id=eq.${session.user.id}`))?.[0];let a=await rest(`addresses?select=*&user_id=eq.${session.user.id}&order=is_default.desc,created_at.desc`);return {p,a:a||[]}}
async function openProfile(){if(!session)return authScreen();try{let d=await profile();show(`<h2>Hesabım</h2><b>${esc(d.p?.full_name||session.user.email)}</b><p>📞 ${esc(d.p?.phone||'')}</p><h3>Kayıtlı Adresler</h3>${d.a.map(a=>`<div class='address'><b>${esc(a.title)}</b><br>${esc(a.address)}</div>`).join('')}<button class='btn secondary' onclick='addressForm()'>+ Yeni Adres</button>${d.p?.role==='admin'?`<a class='btn linkbtn' href='/admin/'>Yönetici Paneli</a>`:''}<button class='btn dark' onclick='logout()'>Çıkış Yap</button>`)}catch(e){alert(e.message)}}
function addressForm(){show(`<h2>Yeni Adres</h2><input id='atitle' class='input' placeholder='Adres adı (Ev, İş)'><textarea id='aaddr' class='input' rows='4' placeholder='Açık adres'></textarea><button class='btn' onclick='saveAddress()'>Adresi Kaydet</button>`)}
async function saveAddress(){try{await rest('addresses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({user_id:session.user.id,title:$('atitle').value||'Adres',address:$('aaddr').value,is_default:false})});openProfile()}catch(e){alert(e.message)}}
function logout(){session=null;localStorage.removeItem('yg_session');closeModal()}
let payment='Kapıda Nakit';async function checkout(){if(!cart.length)return openCart();if(!session)return authScreen('checkout');try{let d=await profile();if(!d.a.length)return addressForm();let total=cart.reduce((s,x)=>s+x.price*x.qty,0);show(`<h2>Teslimat & Ödeme</h2><select id='addrsel' class='input'>${d.a.map(a=>`<option value='${a.id}'>${esc(a.title)} — ${esc(a.address)}</option>`).join('')}</select><h3>Kapıda Ödeme</h3><div class='row'><div id='cash' class='pay sel' onclick="setPay('Kapıda Nakit')">💵<br>Kapıda Nakit</div><div id='card' class='pay' onclick="setPay('Kapıda Kart')">💳<br>Kapıda Kart</div></div><h3>Toplam: ${money(total)}</h3><button class='btn' onclick='placeOrder()'>Siparişi Onayla</button>`)}catch(e){alert(e.message)}}
function setPay(p){payment=p;$('cash').classList.toggle('sel',p==='Kapıda Nakit');$('card').classList.toggle('sel',p==='Kapıda Kart')}
async function placeOrder(){try{let d=await profile(),aid=$('addrsel').value,a=d.a.find(x=>x.id===aid),total=cart.reduce((s,x)=>s+x.price*x.qty,0);let order=(await rest('orders',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:session.user.id,address_id:a.id,customer_name:d.p.full_name,phone:d.p.phone,delivery_address:a.address,payment_method:payment,total})}))?.[0];await rest('order_items',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(cart.map(x=>({order_id:order.id,product_id:x.id,product_name:x.name,quantity:x.qty,unit_price:x.price,line_total:x.price*x.qty})))});cart=[];saveCart();show(`<h2>✅ Siparişiniz Alındı</h2><p>Sipariş numarası: <b>${order.id.slice(0,8)}</b></p><p>Ödeme: ${payment}</p><button class='btn' onclick='closeModal()'>Tamam</button>`)}catch(e){alert('Sipariş kaydedilemedi: '+e.message)}}
async function openOrders(){if(!session)return authScreen();try{let o=await rest(`orders?select=*&user_id=eq.${session.user.id}&order=created_at.desc`);show(`<h2>Siparişlerim</h2>${o.length?o.map(x=>`<div class='order'><b>#${x.id.slice(0,8)}</b> · ${esc(x.status)}<p>${new Date(x.created_at).toLocaleString('tr-TR')}<br>${esc(x.payment_method)} · <b>${money(x.total)}</b></p></div>`).join(''):'<p>Henüz siparişiniz yok.</p>'}`)}catch(e){alert(e.message)}}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn')?.classList.remove('hidden')});$('installBtn')?.addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');boot();
async function changeEmail(newEmail) {
  newEmail = (newEmail || "").trim();

  if (!newEmail || !newEmail.includes("@")) {
    alert("Geçerli bir e-posta adresi girin.");
    return false;
  }

  const { data, error } = await sb.auth.updateUser({
    email: newEmail
  });

  if (error) {
    console.error(error);
    alert("E-posta değiştirilemedi: " + error.message);
    return false;
  }

  alert("E-posta değişikliği gönderildi. Yeni e-posta adresinizi kontrol edin.");
  return true;
}
