-- YILDIZ GROSS MARKET - Supabase production schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', phone text not null default '', role text not null default 'customer' check(role in ('customer','admin')),
  created_at timestamptz not null default now()
);
create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Ev', address text not null, is_default boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.categories (
  id bigint generated by default as identity primary key, name text not null unique, emoji text default '🛒', sort_order int default 0, active boolean default true
);
create table if not exists public.products (
  id bigint generated by default as identity primary key, name text not null, category_id bigint references public.categories(id) on delete set null,
  emoji text default '🛒', image_url text, old_price numeric(12,2), price numeric(12,2) not null check(price>=0), stock int not null default 0,
  active boolean not null default true, featured boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id), address_id uuid references public.addresses(id),
  customer_name text not null, phone text not null, delivery_address text not null, payment_method text not null check(payment_method in ('Kapıda Nakit','Kapıda Kart')),
  total numeric(12,2) not null, status text not null default 'Sipariş Alındı', created_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id bigint generated by default as identity primary key, order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id), product_name text not null, quantity int not null check(quantity>0), unit_price numeric(12,2) not null, line_total numeric(12,2) not null
);

insert into public.categories(name,emoji,sort_order) values
('Süt & Kahvaltı','🥛',1),('Manav','🍎',2),('Et & Tavuk','🥩',3),('İçecek','🥤',4),('Temizlik','🧼',5),('Atıştırmalık','🍫',6),('Kişisel Bakım','🧴',7),('Şarküteri','🧀',8)
on conflict(name) do nothing;

alter table public.profiles enable row level security;
alter table public.addresses enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

drop policy if exists "profiles own read" on public.profiles; create policy "profiles own read" on public.profiles for select using(id=auth.uid() or public.is_admin());
drop policy if exists "profiles own insert" on public.profiles; create policy "profiles own insert" on public.profiles for insert with check(id=auth.uid());
drop policy if exists "profiles own update" on public.profiles; create policy "profiles own update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists "addresses own" on public.addresses; create policy "addresses own" on public.addresses for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
drop policy if exists "categories public read" on public.categories; create policy "categories public read" on public.categories for select using(active=true or public.is_admin());
drop policy if exists "categories admin write" on public.categories; create policy "categories admin write" on public.categories for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "products public read" on public.products; create policy "products public read" on public.products for select using(active=true or public.is_admin());
drop policy if exists "products admin write" on public.products; create policy "products admin write" on public.products for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists "orders own read" on public.orders; create policy "orders own read" on public.orders for select using(user_id=auth.uid() or public.is_admin());
drop policy if exists "orders own insert" on public.orders; create policy "orders own insert" on public.orders for insert with check(user_id=auth.uid());
drop policy if exists "orders admin update" on public.orders; create policy "orders admin update" on public.orders for update using(public.is_admin());
drop policy if exists "items own read" on public.order_items; create policy "items own read" on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_admin())));
drop policy if exists "items own insert" on public.order_items; create policy "items own insert" on public.order_items for insert with check(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));

-- İlk yönetici hesabını oluşturduktan sonra SQL Editor'de şu komutu çalıştırın:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='YONETICI_EMAILINIZ');
